name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter and pytest
        run: |
          make lint
      - name: Test & publish code coverage

        run: |
        uses: paambaati/codeclimate-action@v3.2.0
        if: ${{ github.event_name == 'push' && matrix.os.index == 1 }} # Push coverage only once inside the matrix.
        env:
          CC_TEST_REPORTER_ID: 523ad406c204afe1e906c27e516d231f6d080f7c7a76e4d787c4f1acb30ba38d
        with:
          debug: true